spring:
   datasource:
      url: jdbc:mysql://localhost:3306/news
      username: root
      password: 1111
      driver-class-name: com.mysql.cj.jdbc.Driver
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: create
      properties:
         hibernate:
            format_sql: true
            defer-datasource-initialization: true
            spring:
               jpa:
                  open-in-view: false

#jwt:
#    secret:
#        key: IfthisgetsstolenitsabigproblemIfthelengthistooshortthesecurityisnotsufficientsoanerroroccurs
